### ISSUE TITLE
Got stuck during training

### ISSUE THREAD

**Issue by lxa9867** [google-research/deeplab2#24]
Hi,
Thanks for sharing this great work. I successfully run the evaluating code for max-deeplab but have issues during training. I use two P40 GPU to sanity check the training code with batchsize=2. I didn't change other configs. After I ran the code, I got stuck at "shuffle buffer filled".

The GPU utility is so low so I don't know whether or not it is running and tensorborad keeps blank. 
I am not familiar with TF2 (especially for this pastiche...), could anyone help to figure out what's the problem? Thank you.

BTW, is there any way to make a progress bar like tqdm in pytorch?

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

I changed _SHUFFLE_BUFFER_SIZE=1000 and set it to 50. The "shuffle buffer filled" is ok now.
But still, GPU utility very low & blank tensorboard

I set the summary writer to work every step (maybe summary writer? I used TF1 many years ago)
```
save_checkpoints_steps: 1000
save_summaries_steps: 1 #100
steps_per_loop: 1 #100
```
And...I am very confused that my GPU util is related to the GPU number e.g. 8% for gpu_num=2 and 16% for gpu_num=1...While the GPU memory are fully used no matter what buffer size is

I also tried input size 241x241, it doesn't work. The memory is still full. I think this should be an easy problem, but I am not familiar with TF....

![image](https://user-images.githubusercontent.com/27429220/123391214-5c182e80-d5ce-11eb-86ac-b05c4fbd9053.png)
![image](https://user-images.githubusercontent.com/27429220/123391592-c4ffa680-d5ce-11eb-8a45-3665d2f0fc70.png)

```
(py37tf) mcg@msratiranda:~/deeplab2$ python3 trainer/train.py --config_file=configs/coco/max_deeplab/max_deeplab_s_os16_res1025_200k.textproto --mode=train --model_dir=output --num_gpus=2
2021-06-25 06:55:27.787843: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I0625 06:55:29.205785 140604240011456 train.py:65] Reading the config file.
I0625 06:55:29.208885 140604240011456 train.py:69] Starting the experiment.
2021-06-25 06:55:29.210546: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-06-25 06:55:31.068027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0001:00:00.0 name: Tesla P40 computeCapability: 6.1
coreClock: 1.531GHz coreCount: 30 deviceMemorySize: 22.38GiB deviceMemoryBandwidth: 323.21GiB/s
2021-06-25 06:55:31.069245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties:
pciBusID: 0002:00:00.0 name: Tesla P40 computeCapability: 6.1
coreClock: 1.531GHz coreCount: 30 deviceMemorySize: 22.38GiB deviceMemoryBandwidth: 323.21GiB/s
2021-06-25 06:55:31.069291: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-06-25 06:55:31.072768: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-06-25 06:55:31.072829: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-06-25 06:55:31.074202: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-06-25 06:55:31.074513: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-06-25 06:55:31.077970: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-06-25 06:55:31.078721: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-06-25 06:55:31.078880: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-06-25 06:55:31.083367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2021-06-25 06:55:31.083814: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-25 06:55:31.468479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0001:00:00.0 name: Tesla P40 computeCapability: 6.1
coreClock: 1.531GHz coreCount: 30 deviceMemorySize: 22.38GiB deviceMemoryBandwidth: 323.21GiB/s
2021-06-25 06:55:31.469669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties:
pciBusID: 0002:00:00.0 name: Tesla P40 computeCapability: 6.1
coreClock: 1.531GHz coreCount: 30 deviceMemorySize: 22.38GiB deviceMemoryBandwidth: 323.21GiB/s
2021-06-25 06:55:31.474170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2021-06-25 06:55:31.474253: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-06-25 06:55:32.357293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-25 06:55:32.357388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 1
2021-06-25 06:55:32.357413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N N
2021-06-25 06:55:32.357428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 1:   N N
2021-06-25 06:55:32.363370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22149 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0001:00:00.0, compute capability: 6.1)
2021-06-25 06:55:32.365513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 22149 MB memory) -> physical GPU (device: 1, name: Tesla P40, pci bus id: 0002:00:00.0, compute capability: 6.1)
WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.
W0625 06:55:32.369957 140604240011456 mirrored_strategy.py:379] Collective ops is not configured at program startup. Some performance features may not be enabled.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0625 06:55:32.867475 140604240011456 mirrored_strategy.py:369] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0625 06:55:32.868017 140604240011456 train_lib.py:105] Using strategy <class 'tensorflow.python.distribute.mirrored_strategy.MirroredStrategy'> with 2 replicas
I0625 06:55:32.875228 140604240011456 deeplab.py:57] Synchronized Batchnorm is used.
I0625 06:55:32.876093 140604240011456 axial_resnet_instances.py:144] Axial-ResNet final config: {'num_blocks': [3, 4, 6, 3], 'backbone_layer_multiplier': 1.0, 'width_multiplier': 1.0, 'stem_width_multiplier': 1.0, 'output_stride': 16, 'classification_mode': False, 'backbone_type': 'resnet_beta', 'use_axial_beyond_stride': 16, 'backbone_use_transformer_beyond_stride': 32, 'extra_decoder_use_transformer_beyond_stride': 32, 'backbone_decoder_num_stacks': 0, 'backbone_decoder_blocks_per_stage': 1, 'extra_decoder_num_stacks': 0, 'extra_decoder_blocks_per_stage': 1, 'max_num_mask_slots': 128, 'num_mask_slots': 128, 'memory_channels': 256, 'base_transformer_expansion': 1.0, 'global_feed_forward_network_channels': 256, 'high_resolution_output_stride': 4, 'activation': 'relu', 'block_group_config': {'attention_bottleneck_expansion': 2, 'drop_path_keep_prob': 0.800000011920929, 'drop_path_beyond_stride': 16, 'drop_path_schedule': 'linear', 'positional_encoding_type': None, 'use_global_beyond_stride': 0, 'use_sac_beyond_stride': -1, 'use_squeeze_and_excite': False, 'conv_use_recompute_grad': False, 'axial_use_recompute_grad': True, 'recompute_within_stride': 0, 'transformer_use_recompute_grad': False, 'axial_layer_config': {'query_shape': (129, 129), 'key_expansion': 1, 'value_expansion': 2, 'memory_flange': (32, 32), 'double_global_attention': False, 'num_heads': 8, 'use_query_rpe_similarity': True, 'use_key_rpe_similarity': True, 'use_content_similarity': True, 'retrieve_value_rpe': True, 'retrieve_value_content': True, 'initialization_std_for_query_key_rpe': 1.0, 'initialization_std_for_value_rpe': 1.0, 'self_attention_activation': 'softmax'}, 'dual_path_transformer_layer_config': {'num_heads': 8, 'bottleneck_expansion': 2, 'key_expansion': 1, 'value_expansion': 2, 'feed_forward_network_channels': 2048, 'use_memory_self_attention': True, 'use_pixel2memory_feedback_attention': True, 'transformer_activation': 'softmax'}}, 'bn_layer': functools.partial(<class 'tensorflow.python.keras.layers.normalization_v2.SyncBatchNormalization'>, momentum=0.9900000095367432, epsilon=0.0010000000474974513), 'conv_kernel_weight_decay': 0.0}
I0625 06:55:33.157844 140604240011456 deeplab.py:96] Setting pooling size to (65, 65)
I0625 06:55:33.158083 140604240011456 aspp.py:135] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
decode finish
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.530962 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.532213 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.534660 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.535581 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.538797 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.539653 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.541773 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.542600 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.545866 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0625 06:55:42.546801 140604240011456 cross_device_ops.py:621] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
######### 100
I0625 06:55:42.571589 140604240011456 controller.py:391] restoring or initializing model...
restoring or initializing model...
I0625 06:55:42.608021 140604240011456 controller.py:395] restored model from output/Eval/ckpt-0.
restored model from output/Eval/ckpt-0.
I0625 06:55:42.608137 140604240011456 controller.py:217] restored from checkpoint: output/Eval/ckpt-0
restored from checkpoint: output/Eval/ckpt-0
I0625 06:55:43.796573 140604240011456 api.py:446] Eval with scales ListWrapper([1.0])
I0625 06:55:45.063524 140604240011456 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0625 06:55:45.090902 140604240011456 api.py:446] Eval scale 1.0; setting pooling size to [65, 65]
WARNING:tensorflow:From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
W0625 06:55:48.688872 140604240011456 deprecation.py:534] From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
I0625 06:56:01.794970 140604240011456 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0625 06:56:03.112913 140604240011456 controller.py:236] train | step:      0 | training until step 200000...
train | step:      0 | training until step 200000...
2021-06-25 06:56:04.121265: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-25 06:56:04.122489: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2593990000 Hz
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:05.927121 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:05.949938 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:05.972526 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:06.089528 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:06.111567 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:06.133234 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:06.252249 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:06.278362 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:06.300985 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0625 06:56:06.431849 140604240011456 cross_device_ops.py:903] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
WARNING:tensorflow:From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:206: calling foldl_v2 (from tensorflow.python.ops.functional_ops) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.foldl(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.foldl(fn, elems))
W0625 06:56:43.346125 140596987537152 deprecation.py:601] From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:206: calling foldl_v2 (from tensorflow.python.ops.functional_ops) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.foldl(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.foldl(fn, elems))
WARNING:tensorflow:From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py:463: calling while_loop_v2 (from tensorflow.python.ops.control_flow_ops) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.while_loop(c, b, vars, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))
W0625 06:56:43.658312 140596987537152 deprecation.py:601] From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py:463: calling while_loop_v2 (from tensorflow.python.ops.control_flow_ops) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.while_loop(c, b, vars, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))
2021-06-25 07:01:32.667195: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-06-25 07:01:33.971927: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8100
2021-06-25 07:01:34.548444: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-06-25 07:01:34.911529: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-06-25 07:01:36.659327: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8100
2021-06-25 07:01:46.261119: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 561 of 1000
2021-06-25 07:02:00.735113: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 593 of 1000
2021-06-25 07:02:02.728721: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 619 of 1000
2021-06-25 07:02:15.017214: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 625 of 1000
2021-06-25 07:02:22.714957: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 668 of 1000
2021-06-25 07:02:34.510389: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 718 of 1000
2021-06-25 07:02:42.780139: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 776 of 1000
2021-06-25 07:02:52.867365: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 813 of 1000
2021-06-25 07:03:04.207901: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 874 of 1000
2021-06-25 07:03:12.664182: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 923 of 1000
2021-06-25 07:03:23.321355: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:177] Filling up shuffle buffer (this may take a while): 971 of 1000
2021-06-25 07:03:28.421338: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:230] Shuffle buffer filled.
```

**Comment by lxa9867** [comment]
I changed `_SHUFFLE_BUFFER_SIZE=1000` and set it to 50. The "shuffle buffer filled"  is ok now.
But still, GPU utility very low & blank tensorboard

I set the summary writer to work every step (maybe summary writer? I used TF1 many years ago)
```
  save_checkpoints_steps: 1000
  save_summaries_steps: 1 #100
  steps_per_loop: 1 #100
```

**Comment by csrhddlam** [comment]
Hi, 

Thanks for letting us know this issue.

First of all, the full memory issue is because Tensorflow just occupies all memory while it runs. It doesn't suggest an out-of-memory (OOM) error.

Regarding the stuck issue, are you able to run the basic [resnet-50 config](https://github.com/google-research/deeplab2/blob/main/configs/coco/panoptic_deeplab/resnet50_os16.textproto) on COCO successfully? If yes, could you try replacing [the backbone](https://github.com/google-research/deeplab2/blob/main/configs/coco/panoptic_deeplab/resnet50_os16.textproto#L34) with "max_deeplab_s_backbone" and see if it runs? This gives us more information about where the problem might be.

**Comment by lxa9867** [comment]
Thanks for your reply.

This is the log and GPU utility under resent50 config, I think it runs well.
```
I0626 03:57:13.319347 139850457837760 axial_resnet_instances.py:144] Axial-ResNet final config: {'num_blocks': [3, 4, 6, 3], 'backbone_layer_multiplier': 1.0, 'width_multiplier': 1.0, 'stem_width_multiplier': 1.0, 'output_stride': 16, 'classification_mode': True, 'backbone_type': 'resnet', 'use_axial_beyond_stride': 0, 'backbone_use_transformer_beyond_stride': 0, 'extra_decoder_use_transformer_beyond_stride': 32, 'backbone_decoder_num_stacks': 0, 'backbone_decoder_blocks_per_stage': 1, 'extra_decoder_num_stacks': 0, 'extra_decoder_blocks_per_stage': 1, 'max_num_mask_slots': 128, 'num_mask_slots': 128, 'memory_channels': 256, 'base_transformer_expansion': 1.0, 'global_feed_forward_network_channels': 256, 'high_resolution_output_stride': 4, 'activation': 'relu', 'block_group_config': {'attention_bottleneck_expansion': 2, 'drop_path_keep_prob': 1.0, 'drop_path_beyond_stride': 16, 'drop_path_schedule': 'constant', 'positional_encoding_type': None, 'use_global_beyond_stride': 0, 'use_sac_beyond_stride': -1, 'use_squeeze_and_excite': False, 'conv_use_recompute_grad': False, 'axial_use_recompute_grad': True, 'recompute_within_stride': 0, 'transformer_use_recompute_grad': False, 'axial_layer_config': {'query_shape': (129, 129), 'key_expansion': 1, 'value_expansion': 2, 'memory_flange': (32, 32), 'double_global_attention': False, 'num_heads': 8, 'use_query_rpe_similarity': True, 'use_key_rpe_similarity': True, 'use_content_similarity': True, 'retrieve_value_rpe': True, 'retrieve_value_content': True, 'initialization_std_for_query_key_rpe': 1.0, 'initialization_std_for_value_rpe': 1.0, 'self_attention_activation': 'softmax'}, 'dual_path_transformer_layer_config': {'num_heads': 8, 'bottleneck_expansion': 2, 'key_expansion': 1, 'value_expansion': 2, 'feed_forward_network_channels': 2048, 'use_memory_self_attention': True, 'use_pixel2memory_feedback_attention': True, 'transformer_activation': 'softmax'}}, 'bn_layer': functools.partial(<class 'tensorflow.python.keras.layers.normalization_v2.SyncBatchNormalization'>, momentum=0.9900000095367432, epsilon=0.0010000000474974513), 'conv_kernel_weight_decay': 0.0}
I0626 03:57:13.511222 139850457837760 deeplab.py:96] Setting pooling size to (41, 41)
I0626 03:57:13.511468 139850457837760 aspp.py:135] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:57:13.511590 139850457837760 aspp.py:135] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
WARNING:tensorflow:From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
W0626 03:57:17.840097 139850457837760 deprecation.py:534] From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
######### 100
I0626 03:57:20.698017 139850457837760 controller.py:391] restoring or initializing model...
restoring or initializing model...
I0626 03:57:20.698222 139850457837760 controller.py:397] initialized model.
initialized model.
I0626 03:57:21.889940 139850457837760 api.py:446] Eval with scales ListWrapper([1.0])
I0626 03:57:23.253040 139850457837760 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:57:23.282651 139850457837760 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:57:23.310259 139850457837760 api.py:446] Eval scale 1.0; setting pooling size to [41, 41]
I0626 03:57:28.292841 139850457837760 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:57:28.322828 139850457837760 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:57:30.499344 139850457837760 controller.py:487] saved checkpoint to output/panoptic_resnet50_os16/ckpt-0.
saved checkpoint to output/panoptic_resnet50_os16/ckpt-0.
I0626 03:57:30.499933 139850457837760 controller.py:236] train | step:      0 | training until step 200000...
train | step:      0 | training until step 200000...
2021-06-26 03:57:30.978694: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-26 03:57:30.979509: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2593990000 Hz
2021-06-26 03:58:10.995738: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-06-26 03:58:11.336968: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8100
2021-06-26 03:58:11.732933: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-06-26 03:58:12.006126: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
I0626 03:59:31.502029 139850457837760 controller.py:458] train | step:    100 | steps/sec:    0.8 | output:
    {'learning_rate': 2.5000001e-05,
     'losses/train_center_loss': 1.6140642,
     'losses/train_regression_loss': 0.5272915,
     'losses/train_semantic_loss': 5.4412446,
     'losses/train_total_loss': 7.5826}
train | step:    100 | steps/sec:    0.8 | output:
    {'learning_rate': 2.5000001e-05,
     'losses/train_center_loss': 1.6140642,
     'losses/train_regression_loss': 0.5272915,
     'losses/train_semantic_loss': 5.4412446,
     'losses/train_total_loss': 7.5826}

```
![image](https://user-images.githubusercontent.com/27429220/123501218-e8316100-d675-11eb-9326-8d2927052e4e.png)

After I change the backbone to "max_deeplab_s", it also runs well.
```
I0626 03:49:47.413747 139760778813632 axial_resnet_instances.py:144] Axial-ResNet final config: {'num_blocks': [3, 4, 6, 3], 'backbone_layer_multiplier': 1.0, 'width_multiplier': 1.0, 'stem_width_multiplier': 1.0, 'output_stride': 16, 'classification_mode': True, 'backbone_type': 'resnet_beta', 'use_axial_beyond_stride': 16, 'backbone_use_transformer_beyond_stride': 0, 'extra_decoder_use_transformer_beyond_stride': 32, 'backbone_decoder_num_stacks': 0, 'backbone_decoder_blocks_per_stage': 1, 'extra_decoder_num_stacks': 0, 'extra_decoder_blocks_per_stage': 1, 'max_num_mask_slots': 128, 'num_mask_slots': 128, 'memory_channels': 256, 'base_transformer_expansion': 1.0, 'global_feed_forward_network_channels': 256, 'high_resolution_output_stride': 4, 'activation': 'relu', 'block_group_config': {'attention_bottleneck_expansion': 2, 'drop_path_keep_prob': 1.0, 'drop_path_beyond_stride': 16, 'drop_path_schedule': 'constant', 'positional_encoding_type': None, 'use_global_beyond_stride': 0, 'use_sac_beyond_stride': -1, 'use_squeeze_and_excite': False, 'conv_use_recompute_grad': False, 'axial_use_recompute_grad': True, 'recompute_within_stride': 0, 'transformer_use_recompute_grad': False, 'axial_layer_config': {'query_shape': (129, 129), 'key_expansion': 1, 'value_expansion': 2, 'memory_flange': (32, 32), 'double_global_attention': False, 'num_heads': 8, 'use_query_rpe_similarity': True, 'use_key_rpe_similarity': True, 'use_content_similarity': True, 'retrieve_value_rpe': True, 'retrieve_value_content': True, 'initialization_std_for_query_key_rpe': 1.0, 'initialization_std_for_value_rpe': 1.0, 'self_attention_activation': 'softmax'}, 'dual_path_transformer_layer_config': {'num_heads': 8, 'bottleneck_expansion': 2, 'key_expansion': 1, 'value_expansion': 2, 'feed_forward_network_channels': 2048, 'use_memory_self_attention': True, 'use_pixel2memory_feedback_attention': True, 'transformer_activation': 'softmax'}}, 'bn_layer': functools.partial(<class 'tensorflow.python.keras.layers.normalization_v2.SyncBatchNormalization'>, momentum=0.9900000095367432, epsilon=0.0010000000474974513), 'conv_kernel_weight_decay': 0.0}
I0626 03:49:47.644548 139760778813632 deeplab.py:96] Setting pooling size to (41, 41)
I0626 03:49:47.644795 139760778813632 aspp.py:135] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:49:47.644916 139760778813632 aspp.py:135] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
WARNING:tensorflow:From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
W0626 03:49:52.028648 139760778813632 deprecation.py:534] From /home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
######### 100
I0626 03:49:54.941907 139760778813632 controller.py:391] restoring or initializing model...
restoring or initializing model...
I0626 03:49:54.942111 139760778813632 controller.py:397] initialized model.
initialized model.
I0626 03:49:56.121497 139760778813632 api.py:446] Eval with scales ListWrapper([1.0])
I0626 03:49:57.515579 139760778813632 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:49:57.544761 139760778813632 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:49:57.572241 139760778813632 api.py:446] Eval scale 1.0; setting pooling size to [41, 41]
I0626 03:50:05.040328 139760778813632 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:50:05.070598 139760778813632 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0626 03:50:07.557797 139760778813632 controller.py:487] saved checkpoint to output/panoptic_resnet50_os16/ckpt-0.
saved checkpoint to output/panoptic_resnet50_os16/ckpt-0.
I0626 03:50:07.558384 139760778813632 controller.py:236] train | step:      0 | training until step 200000...
train | step:      0 | training until step 200000...
2021-06-26 03:50:08.046499: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-26 03:50:08.047468: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2593990000 Hz
2021-06-26 03:51:25.691272: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-06-26 03:51:26.297113: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8100
2021-06-26 03:51:26.674273: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-06-26 03:51:26.948483: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11



I0626 03:53:33.448543 139760778813632 controller.py:458] train | step:    100 | steps/sec:    0.5 | output:
    {'learning_rate': 2.5000001e-05,
     'losses/train_center_loss': nan,
     'losses/train_regression_loss': nan,
     'losses/train_semantic_loss': nan,
     'losses/train_total_loss': nan}
train | step:    100 | steps/sec:    0.5 | output:
    {'learning_rate': 2.5000001e-05,
     'losses/train_center_loss': nan,
     'losses/train_regression_loss': nan,
     'losses/train_semantic_loss': nan,
     'losses/train_total_loss': nan}
I0626 03:55:37.245568 139760778813632 controller.py:458] train | step:    200 | steps/sec:    0.8 | output:
    {'learning_rate': 5.0000002e-05,
     'losses/train_center_loss': nan,
     'losses/train_regression_loss': nan,
     'losses/train_semantic_loss': nan,
     'losses/train_total_loss': nan}
train | step:    200 | steps/sec:    0.8 | output:
    {'learning_rate': 5.0000002e-05,
     'losses/train_center_loss': nan,
     'losses/train_regression_loss': nan,
     'losses/train_semantic_loss': nan,
     'losses/train_total_loss': nan}
```
![image](https://user-images.githubusercontent.com/27429220/123501167-8113ac80-d675-11eb-9225-8f0a3e10c076.png)

**Comment by lxa9867** [comment]
I create a docker image for you to reproduce the issue. It can reproduce the stuck issue for max-deeplab and also successfully run panoptic deeplab resnet50 version. You may pull the docker from`ang9867/max_tf`.

This docker is built upon `tensorflow/tensorflow:2.5.0-gpu`. I have installed all required packages. But you still need to setup the path to Orbit and cocoapi. 
```
docker pull ang9867/max_tf
docker run -it --gpus all -v $deeplab2 path host$:$deeplab2 path in docker$ -v $data folder path in host$:$data folder path indocker$ ang9867/max_tf /bin/bash
cd $path to cocoapi$/cocoapi/PythonAPI
make
cd ../..
export PYTHONPATH=$PYTHONPATH:$path to deeplab2$:$path to models$/models:$path to cocoapi$/cocoapi/PythonAPI
python3 trainer/train.py --config_file=configs/coco/max_deeplab/max_deeplab_s_os16_res641_400k.textproto --mode=train --model_dir=output --num_gpus=1
```

**Comment by csrhddlam** [comment]
The docker image looks great! Thanks for sharing it.

I'll try it on my machine and get back to you later.

**Comment by lxa9867** [comment]
Thx!

I suppose the matching operation makes the stuck (stuck because of Orbit, and should throw up an error). I disabled the loop in Orbit, and run it in single step. It turns out to the following errors. Hope for your feedback.
'''
2021-06-26 09:57:53.491916: W tensorflow/core/common_runtime/bfc_allocator.cc:467] ****************************************************************************************************
2021-06-26 09:57:53.492005: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at base_op.h:129 : Invalid argument: input and output shapes/data type sizes are not compatible
Traceback (most recent call last):
  File "trainer/train.py", line 76, in <module>
    app.run(main)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "trainer/train.py", line 72, in main
    FLAGS.num_gpus)
  File "/home/mcg/deeplab2/trainer/train_lib.py", line 187, in run_experiment
    steps=config.trainer_options.solver_options.training_number_of_steps)
  File "/home/mcg/deeplab2/models/orbit/controller.py", line 241, in train
    self._train_n_steps(num_steps)
  File "/home/mcg/deeplab2/models/orbit/controller.py", line 440, in _train_n_steps
    train_output = self.trainer.train(num_steps_tensor)
  File "/home/mcg/deeplab2/models/orbit/standard_runner.py", line 153, in train
    self.train_step(self._train_iter)
  File "/home/mcg/deeplab2/trainer/trainer.py", line 221, in train_step
    self._strategy.run(step_fn, args=(next(iterator),))
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/distribute/one_device_strategy.py", line 188, in run
    return super(OneDeviceStrategy, self).run(fn, args, kwargs, options)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1285, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2833, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/distribute/one_device_strategy.py", line 396, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 597, in wrapper
    return func(*args, **kwargs)
  File "/home/mcg/deeplab2/trainer/trainer.py", line 219, in step_fn
    self._train_step(inputs)
  File "/home/mcg/deeplab2/trainer/trainer.py", line 238, in _train_step
    loss_dict = self._loss(inputs, outputs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/mcg/deeplab2/model/loss/loss_builder.py", line 207, in call
    loss_dict = multi_term_loss((y_true, y_pred))
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/mcg/deeplab2/model/loss/max_deeplab_loss.py", line 605, in call
    nonsquare_hungarian_matching(hungarian_weights))
  File "/home/mcg/deeplab2/model/loss/max_deeplab_loss.py", line 139, in nonsquare_hungarian_matching
    square_permutation = matchers_ops.hungarian_matching(weights)
  File "/home/mcg/deeplab2/model/loss/matchers_ops.py", line 513, in hungarian_matching
    back_prop=False)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2541, in while_loop_v2
    return_same_structure=True)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2777, in while_loop
    loop_vars = body(*loop_vars)
  File "/home/mcg/deeplab2/model/loss/matchers_ops.py", line 501, in _update_weights_and_match
    adj_matrix = tf.equal(weights, 0.)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 1729, in equal
    return gen_math_ops.equal(x, y, name=name)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 3215, in equal
    _ops.raise_from_not_ok_status(e, name)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: input and output shapes/data type sizes are not compatible [Op:Equal]
2021-06-26 09:57:53.840640: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-06-26 09:57:53.840712: F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1
Fatal Python error: Aborted

Thread 0x00007fa83d1620c0 (most recent call first):
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1264 in delete_iterator
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 546 in __del__
Aborted (core dumped)
'''

**Comment by csrhddlam** [comment]
Thanks for pinpointing the issue! This is really helpful.

It seems to me that the 0. is not correctly converted to a float32 tensor.

While I am looking more closely into the issue, a fix could be to use an explicit `tf.constant(0.0, dtype=tf.float32)` instead of the 0. at [line 470](https://github.com/google-research/deeplab2/blob/main/model/loss/matchers_ops.py#L470) and [line 483](https://github.com/google-research/deeplab2/blob/main/model/loss/matchers_ops.py#L483).

**Comment by lxa9867** [comment]
I tried to replace `0.0` with `tf.constant(0.0, dtype=tf.float32)` but the error keeps the same. Then I tried `tf.constant(0.0, dtype=weights.dtype)`, the error changes. But still have errors in matcher_ops.py, which outputs thousands of lines like 
```
2021-06-26 15:10:21.042821: I tensorflow/core/common_runtime/bfc_allocator.cc:1054] 6 Chunks of size 4286720 totalling 24.53MiB
2021-06-26 15:10:21.042831: I tensorflow/core/common_runtime/bfc_allocator.cc:1054] 1 Chunks of size 4456704 totalling 4.25MiB
```
Then it turns out to
```
2021-06-26 15:20:03.694437: W tensorflow/core/common_runtime/bfc_allocator.cc:467] ****************************************************************************************************
2021-06-26 15:20:03.694569: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at base_op.h:129 : Invalid argument: input and output shapes/data type sizes are not compatible
Traceback (most recent call last):
  File "trainer/train.py", line 76, in <module>
    app.run(main)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "trainer/train.py", line 72, in main
    FLAGS.num_gpus)
  File "/home/mcg/deeplab2/trainer/train_lib.py", line 187, in run_experiment
    steps=config.trainer_options.solver_options.training_number_of_steps)
  File "/home/mcg/deeplab2/models/orbit/controller.py", line 241, in train
    self._train_n_steps(num_steps)
  File "/home/mcg/deeplab2/models/orbit/controller.py", line 440, in _train_n_steps
    train_output = self.trainer.train(num_steps_tensor)
  File "/home/mcg/deeplab2/models/orbit/standard_runner.py", line 153, in train
    self.train_step(self._train_iter)
  File "/home/mcg/deeplab2/trainer/trainer.py", line 221, in train_step
    self._strategy.run(step_fn, args=(next(iterator),))
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/distribute/one_device_strategy.py", line 188, in run
    return super(OneDeviceStrategy, self).run(fn, args, kwargs, options)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1285, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2833, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/distribute/one_device_strategy.py", line 396, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 597, in wrapper
    return func(*args, **kwargs)
  File "/home/mcg/deeplab2/trainer/trainer.py", line 219, in step_fn
    self._train_step(inputs)
  File "/home/mcg/deeplab2/trainer/trainer.py", line 238, in _train_step
    loss_dict = self._loss(inputs, outputs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/mcg/deeplab2/model/loss/loss_builder.py", line 207, in call
    loss_dict = multi_term_loss((y_true, y_pred))
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/mcg/deeplab2/model/loss/max_deeplab_loss.py", line 605, in call
    nonsquare_hungarian_matching(hungarian_weights))
  File "/home/mcg/deeplab2/model/loss/max_deeplab_loss.py", line 139, in nonsquare_hungarian_matching
    square_permutation = matchers_ops.hungarian_matching(weights)
  File "/home/mcg/deeplab2/model/loss/matchers_ops.py", line 515, in hungarian_matching
    back_prop=False)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2541, in while_loop_v2
    return_same_structure=True)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2777, in while_loop
    loop_vars = body(*loop_vars)
  File "/home/mcg/deeplab2/model/loss/matchers_ops.py", line 503, in _update_weights_and_match
    adj_matrix = tf.equal(weights, tf.constant(0.0, dtype=weights.dtype))
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 1729, in equal
    return gen_math_ops.equal(x, y, name=name)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 3215, in equal
    _ops.raise_from_not_ok_status(e, name)
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: input and output shapes/data type sizes are not compatible [Op:Equal]
2021-06-26 15:20:04.257207: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-06-26 15:20:04.257269: F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1
Fatal Python error: Aborted

Thread 0x00007fcf86f650c0 (most recent call first):
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1264 in delete_iterator
  File "/home/mcg/miniconda3/envs/py37tf/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 546 in __del__
Aborted (core dumped)
```

**Comment by csrhddlam** [comment]
Just found out why! Finally!

In short, this is caused by a bug in [SyncBatchNormalization](tf.keras.layers.experimental.SyncBatchNormalization). The bug was fixed by us during the development of DeepLab2. However, [the fix](https://github.com/tensorflow/tensorflow/commit/f5ead6f8e4de470fcf140360b304a4d788198090), unfortunately, was not included in the tensorflow 2.5 release, which is used in your docker image.

A quick verification of the bug causing the issue is to insert `use_sync_batchnorm: false` in the [config](https://github.com/google-research/deeplab2/blob/main/configs/coco/max_deeplab/max_deeplab_s_os16_res641_100k.textproto#L85). The training should run successfully with this quick work around.

Solution: the issue should be resolved if a newer version tensorflow that includes the fix commit is used, e.g., [tensorflow 2.6](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) or [tensorflow github master](https://github.com/tensorflow/tensorflow).

Explanation: The bug in SyncBatchNormalization causes nan batch norm outputs in attention layers (as verified by your Panoptic-DeepLab experiment with `max_deeplab_s_backbone`), and thus the network outputs are mostly nan. These nan outputs caused all the errors in hungarian matching.

**Comment by lxa9867** [comment]
Thank you! 

TF 2.6 works!
